### ISSUE TITLE
Reduce long line

### ISSUE THREAD

**Issue by henrikmdev** [CapioIM/ReverseString#1]
https://github.com/CapioIM/ReverseString/blob/58976b7d01166134f9e281aadc7c8614dcff999d/ReverseString/Program.cs#L41-L42

My main issue with this is that it's a long line, but it also seems like an inefficient way to do this.
Can you use a different way of removing these characters?

Some ideas:
-Split method to delimit your string with the characters you want to remove. The join using the Join method.
- Using a foreach loop and an array of all the characters you want to remove. Then in the foreach loop remove the characters specified in the array.

**Comment by CapioIM** [comment]
Removed special characters with RagEx , .Contains() , .Split() and .Join()
