### ISSUE TITLE
Test cases don't pass

### ISSUE THREAD

**Issue by henrikmdev** [CapioIM/ReverseString#4]
https://github.com/CapioIM/ReverseString/blob/58976b7d01166134f9e281aadc7c8614dcff999d/ReverseString/Program.cs#L10
https://github.com/CapioIM/ReverseString/blob/58976b7d01166134f9e281aadc7c8614dcff999d/ReverseString/Program.cs#L12

I assume you mean for these to pass the palindrome test, but they don't. Here is my output when testing with them:

Or just letters in reverse: ”alletsdellacalledstella
This word or sentence is NOT Palindrome, which means it doesn't read same backwards!

Or just letters in reverse: arewenotpurenosirpa—namasmoodynori”egabragsitisgarbageironydooms’amanap”risoneruptonewera
This word or sentence is NOT Palindrome, which means it doesn't read same backwards!

And I don't think you expect "1961" to pass, but you just noted it down because it looks the same upside down?

**Comment by CapioIM** [comment]
1961, I didn't expect to pass, since my thought to replace 9 with 6 is not good idea
